package com.example.chat_web_socket.providers;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Map;

@SpringBootTest
public class JsonWebTokenProviderTest {

    @Autowired
    private TokenProvider tokenProvider;

    @Test
    void teste() {
        Map<String, String> decoded = tokenProvider.decode("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJUZzVOalExTWpnNU16UTNSRFkxTWprd1JUaEdSakV4UXpBeE1UazFOa05CUkRaRE5UaEVOdyJ9.eyJnaXZlbl9uYW1lIjoiZXZlcnRvbiIsImZhbWlseV9uYW1lIjoibGVtb3MiLCJuaWNrbmFtZSI6ImUuaGRlbGVtb3MiLCJuYW1lIjoiZXZlcnRvbiBsZW1vcyIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NJXzlYMjg0UENuMURDRGptVkt3eVlNR25mMy05RUVIUVNmcmowSE5rM2IyOVRvWmc9czk2LWMiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wNi0xMlQxMjoyNDoxMy4zMjZaIiwiZW1haWwiOiJlLmhkZWxlbW9zQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL25ld2NhaW9zYW50b3MuYXV0aDAuY29tLyIsImF1ZCI6IlNJR1MzenZwRkpGNFB6YnB4WndpZGZBMGNVUjNCOGE0IiwiaWF0IjoxNzE4MTk1MDYyLCJleHAiOjE3MTgxOTg2NjIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA2MTUwMTkyNDcxODkyODA4ODY2Iiwic2lkIjoicjczMDdQdkhzNjdIamFJbDZMYVhGcHJIUXNGSDVDR2oiLCJub25jZSI6IlpsQlZUV0ZZTFRGcFFqbHRTSGwxZUZObk5XRk5WVWR4TVRaM1JrMTRSakJ0WjJKVWJraDFhVk5CU2c9PSJ9.AFfrR8SW0pSeM5m3UEZSAZ1cZnVQbp8f7d79VNfuBbN68s1OwHBXSKL1FK3FRnGbT4Rus7sO494j9TO6TdAbv1NsI3iZBfESZMM4Sep4lTmV7hv0tMmNAFXFuc4IUTMdHbwik0pEi6xvDjzevZqpKgZS8EmHcTzFPdXyNiNZC97-dJShDx3P1C-noZJTsssO6BhkOxOMpiwveq7bBuMEKxirYPMSPaxSessPzYwwN5DFeTiaWSqxVy8TA7Sd_yZI7Q4jcM9aI6JPwEcLjqb7UXvS1KIBTmNZevGpzdNvVi4DfTrb_FJGv-9tfu5n-gXESfgQLLRXoyE1jXYG70z-Tg");
        System.out.println(decoded);
    }
}
