spring :
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 100000

app:
  auth:
    jwks-url: https://dev-x4c8ir4qiuaa1hmd.us.auth0.com/.well-known/jwks.json
